# Generated by Django 4.1.1 on 2022-09-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.TextField(null=True)),
                ('nivel', models.CharField(choices=[('Técnico', 'Técnico'), ('Grado', 'Grado'), ('Post-grado', 'Post-grado'), ('Doctorado', 'Doctorado'), ('Gestión', 'Gestión'), ('Maestría', 'Maestría')], max_length=200, null=True)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('institucion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='compentencia',
            name='DescripCompetencia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
