# Generated by Django 4.1.1 on 2022-09-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0002_capacitacion_alter_compentencia_descripcompetencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Maestría', 'Maestría'), ('Grado', 'Grado'), ('Doctorado', 'Doctorado'), ('Gestión', 'Gestión'), ('Técnico', 'Técnico'), ('Post-grado', 'Post-grado')], max_length=200, null=True),
        ),
    ]
