# Generated by Django 4.1.1 on 2022-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0003_alter_capacitacion_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=50, null=True)),
                ('nivelRiesgo', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True)),
                ('nivelMinimoSalario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivelMaximoSalario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='capacitacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='institucion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Gestión', 'Gestión'), ('Técnico', 'Técnico'), ('Doctorado', 'Doctorado'), ('Maestría', 'Maestría'), ('Grado', 'Grado'), ('Post-grado', 'Post-grado')], max_length=12, null=True),
        ),
    ]
