# Generated by Django 4.1.1 on 2022-10-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0008_alter_capacitacion_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='principalesCapacitacion',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Doctorado', 'Doctorado'), ('Post-grado', 'Post-grado'), ('Técnico', 'Técnico'), ('Maestría', 'Maestría'), ('Gestión', 'Gestión'), ('Grado', 'Grado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='compentencia',
            name='descripCompetencia',
            field=models.CharField(max_length=200, null=True, verbose_name='Competencia'),
        ),
        migrations.AlterField(
            model_name='compentencia',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='principalesCapacitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='msrh.capacitacion'),
        ),
    ]
