# Generated by Django 4.1.1 on 2022-10-11 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0010_remove_candidato_principalescapacitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='recomendacion',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Técnico', 'Técnico'), ('Doctorado', 'Doctorado'), ('Post-grado', 'Post-grado'), ('Maestría', 'Maestría'), ('Gestión', 'Gestión')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='recomendacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh.empleado'),
        ),
    ]
