# Generated by Django 4.1.1 on 2022-10-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0011_remove_candidato_recomendacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='puestoAspira',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Post-grado', 'Post-grado'), ('Grado', 'Grado'), ('Técnico', 'Técnico'), ('Doctorado', 'Doctorado'), ('Gestión', 'Gestión'), ('Maestría', 'Maestría')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Bajo', 'Bajo'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='puestoAspira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh.puesto'),
        ),
    ]
