# Generated by Django 4.1.1 on 2022-10-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msrh', '0013_alter_capacitacion_nivel_alter_puesto_nivelriesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Doctorado', 'Doctorado'), ('Post-grado', 'Post-grado'), ('Gestión', 'Gestión'), ('Grado', 'Grado'), ('Técnico', 'Técnico'), ('Maestría', 'Maestría')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Alto', 'Alto'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
    ]
