# Generated by Django 4.1.1 on 2022-10-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0014_candidato_user_alter_capacitacion_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Gestión', 'Gestión'), ('Técnico', 'Técnico'), ('Post-grado', 'Post-grado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Alto', 'Alto'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
