# Generated by Django 4.1.1 on 2022-10-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0016_remove_candidato_user_candidato_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Grado', 'Grado'), ('Post-grado', 'Post-grado'), ('Gestión', 'Gestión'), ('Técnico', 'Técnico')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Alto', 'Alto'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
