# Generated by Django 4.1.1 on 2022-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0019_alter_capacitacion_nivel_alter_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cedula',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Post-grado', 'Post-grado'), ('Doctorado', 'Doctorado'), ('Técnico', 'Técnico'), ('Gestión', 'Gestión'), ('Maestría', 'Maestría'), ('Grado', 'Grado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Bajo', 'Bajo'), ('Medio', 'Medio')], max_length=5, null=True),
        ),
    ]
