# Generated by Django 4.1.1 on 2022-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0020_alter_candidato_cedula_alter_capacitacion_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Doctorado', 'Doctorado'), ('Maestría', 'Maestría'), ('Gestión', 'Gestión'), ('Técnico', 'Técnico'), ('Grado', 'Grado'), ('Post-grado', 'Post-grado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Alto', 'Alto')], max_length=5, null=True),
        ),
    ]
