# Generated by Django 4.1.1 on 2022-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0021_alter_capacitacion_nivel_alter_puesto_nivelriesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Doctorado', 'Doctorado'), ('Post-grado', 'Post-grado'), ('Técnico', 'Técnico'), ('Gestión', 'Gestión'), ('Maestría', 'Maestría')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Alto', 'Alto'), ('Bajo', 'Bajo')], max_length=5, null=True),
        ),
    ]
