# Generated by Django 4.1.1 on 2022-10-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0022_alter_capacitacion_nivel_alter_empleado_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='idioma',
            field=models.ManyToManyField(to='msrh.idioma'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cedula',
            field=models.CharField(max_length=13, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='departamento',
            field=models.CharField(max_length=60, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='expeiencia',
            field=models.ManyToManyField(to='msrh.experiencialaboral', verbose_name='Experiencia Laboral'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(max_length=60, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='principalesCapacitacion',
            field=models.ManyToManyField(to='msrh.capacitacion', verbose_name='Principales '),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='principalesCompetencia',
            field=models.ManyToManyField(to='msrh.compentencia', verbose_name='Principales Competencias'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='puestoAspira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh.puesto', verbose_name='Puesto que Aspira'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='recomendacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh.empleado', verbose_name='Recomendado por'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='capacitacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Capacitación'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='fechaDesde',
            field=models.DateField(verbose_name='Fecha Desde'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='fechaHasta',
            field=models.DateField(verbose_name='Fecha Hasta'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='institucion',
            field=models.CharField(max_length=50, null=True, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Post-grado', 'Post-grado'), ('Maestría', 'Maestría'), ('Técnico', 'Técnico'), ('Doctorado', 'Doctorado'), ('Gestión', 'Gestión')], max_length=12, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=13, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=60, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh.puesto', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salarioMensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mensual'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(max_length=200, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechaDesde',
            field=models.DateField(verbose_name='Fecha Desde'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechaHasta',
            field=models.DateField(verbose_name='Fecha Hasta'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='puestoOcupado',
            field=models.CharField(max_length=200, null=True, verbose_name='Puesto Ocupado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(max_length=200, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelMaximoSalario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Máximo'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelMinimoSalario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=5, null=True, verbose_name='Nivel Riesgo'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='puesto',
            field=models.CharField(max_length=50, null=True, verbose_name='Puesto'),
        ),
    ]
