# Generated by Django 4.1.1 on 2022-10-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0023_candidato_idioma_alter_candidato_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Doctorado', 'Doctorado'), ('Técnico', 'Técnico'), ('Maestría', 'Maestría'), ('Gestión', 'Gestión'), ('Post-grado', 'Post-grado'), ('Grado', 'Grado')], max_length=12, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Alto', 'Alto'), ('Bajo', 'Bajo')], max_length=5, null=True, verbose_name='Nivel Riesgo'),
        ),
    ]
