# Generated by Django 4.1.1 on 2022-10-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0024_alter_capacitacion_nivel_alter_puesto_nivelriesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Grado', 'Grado'), ('Maestría', 'Maestría'), ('Post-grado', 'Post-grado'), ('Gestión', 'Gestión'), ('Técnico', 'Técnico'), ('Doctorado', 'Doctorado')], max_length=12, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Bajo', 'Bajo'), ('Medio', 'Medio')], max_length=5, null=True, verbose_name='Nivel Riesgo'),
        ),
    ]
