# Generated by Django 4.1.1 on 2022-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0025_alter_capacitacion_nivel_alter_puesto_nivelriesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Doctorado', 'Doctorado'), ('Maestría', 'Maestría'), ('Técnico', 'Técnico'), ('Grado', 'Grado'), ('Post-grado', 'Post-grado'), ('Gestión', 'Gestión')], max_length=12, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nivelRiesgo',
            field=models.CharField(choices=[('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Alto', 'Alto')], max_length=5, null=True, verbose_name='Nivel Riesgo'),
        ),
    ]
