# Generated by Django 4.1.1 on 2022-10-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh', '0027_alter_capacitacion_nivel_alter_puesto_nivelriesgo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='idioma',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='nivel',
            field=models.CharField(choices=[('Post-grado', 'Post-grado'), ('Técnico', 'Técnico'), ('Grado', 'Grado'), ('Doctorado', 'Doctorado'), ('Maestría', 'Maestría'), ('Gestión', 'Gestión')], max_length=12, null=True, verbose_name='Nivel'),
        ),
    ]
